name: Ping URL
description: Ping URL until maximum trials have exceed. If the result is not 200, until then fails the action.

inputs:
  # INPUT_URL
  url:
    description: URL to ping.
    required: true

  # INPUT_MAX_TRIALS
  max_trials:
    description: Maximum number of trials until the action fails.
    default: '10'
    required: false

  # INPUT_DELAY
  delay:
    description: Delay in seconds between the trials.
    default: '5'
    required: false

outputs:
  url-reachable:
    description: Whether the URL is reachable
runs:
  using: docker
  image: Dockerfile
