name: 06 - Contexts
run-name: 06 - Contexts | DEBUG ${{inputs.debug}}

on:
  push:
  workflow_dispatch:
   inputs:
      debug:
         type: boolean
         default: false

env:
   MY_WORKFLOW_VAR: "Workflow-variable"
   MY_OVERWRITTEN_VAR: "Workflow-variable"

jobs:
   echo-data:
      runs-on: ubuntu-latest
      env:
         MY_JOB_VAR: "Job-variable"
         MY_OVERWRITTEN_VAR: "Overwritten-variable"

      steps:
         - name: Display Information
           run: |
            echo "Event name: ${{github.event_name}}"
            echo "Ref: ${{github.ref}}"
            echo "SHA: ${{github.sha}}"
            echo "Actor: ${{github.actor}}"
            echo "Workflow: ${{github.workflow}}"
            echo "Run ID: ${{github.run_id}}"
            echo "Run number: ${{github.run_number}}"

         - name: Retrieve Variables
           run: |
            echo "variable value: ${{vars.HELLO_VAR}}"
         - name: Print Env Variables
           run: |
            echo "workflow variable: ${{env.MY_WORKFLOW_VAR}}"
            echo "Overwritten variable: ${{env.MY_OVERWRITTEN_VAR}}"
            echo "Job variable: ${{env.MY_JOB_VAR}}"
