name: 07 - Expressions
run-name: 07 - Expressions | DEBUG ${{ inputs.debug && 'ON' || 'OFF' }}

on:
   push:
   workflow_dispatch:
      inputs:
         debug:
            type: boolean
            default: false

jobs:
   echo:
      runs-on: ubuntu-latest
      steps:
         - name: "[debug] Print start-up data"
           if: ${{ inputs.debug == false }}
           run: |
              echo "Triggered by ${{ github.event_name }}"
              echo "Branch: ${{ github.ref }}"
              echo "Commit SHA: ${{ github.sha }}"
              echo "Runner OS: ${{ runner.os }}"
         - name: "[debug] Print when triggered from dev"
           if: ${{ !inputs.debug && github.ref == 'refs/heads/dev' }}
           run: echo "This is triggered from dev"
         - name: greetings
           run: echo "Hello, World!"