name: 11 - Inputs

on:
  workflow_dispatch:
    # There are 3 types of input under workflow_dispatch: boolean, environment, and choice
    inputs:
      dry-run:
        type: boolean
        description: Skip deployment and only print build output
        default: false
      target:
        type: environment
        required: true
        description: Which environment that the workflow targets
      tag:
        type: choice
        options:
          - v1
          - v2
          - v3
        default: v3
        description: Release from which to build and deploy

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building from release ${{ inputs.tag }}"
  deploy:
      runs-on: ubuntu-latest
      if: ${{ !inputs.dry-run }}
      environment: ${{ inputs.target }}
      steps:
        - name: Deploy
          run: echo "Deploying to ${{ inputs.target }}"