name: 13 - Caching

on:
  workflow_dispatch:
    inputs:
      use-cache:
        description: Whether to execute the cache step
        type: boolean
        default: true
      node-version:
        description: Node versions
        type: choice
        options:
          - 19.x
          - 20.x
          - 21.x
        default: 20.x

# 1. Checkout the code
# 2. Install dependencies
# 3. Lint, Format, Test, Build
# 4. Deploy to the nonprod environment

jobs:
  install-deps:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: "apps/react-app"
    outputs:
      deps-cache-key: ${{steps.cache-key.outputs.CACHE_KEY}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{inputs.node-version}}"
      - name: Calculate cache key
        id: cache-key
        run: |
          echo "CACHE_KEY=deps-node-modules-${{hashFiles('apps/react-app/package-lock.json')}}"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache
        with:
          path: apps/react-app/node_modules
          key: ${{steps.cache-key.outputs.CACHE_KEY}}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm ci
  lint-test:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: "apps/react-app"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{inputs.node-version}}"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache
        with:
          path: apps/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying to nonprod..."

  build:
    runs-on: ubuntu-latest
    needs: install-deps
    defaults:
      run:
        working-directory: "apps/react-app"
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "${{inputs.node-version}}"
      - name: Download cached dependencies
        uses: actions/cache@v3
        if: ${{inputs.use-cache}}
        id: cache
        with:
          path: apps/react-app/node_modules
          key: ${{needs.install-deps.outputs.deps-cache-key}}
      - name: Build
        run: npm run build
      - name: Deploy
        run: echo "Deploying to nonprod..."
