name: 16 - Environments
run-name: 16 - Environments | env - ${{inputs.target-env}}

on:
  workflow_dispatch:
    inputs:
      target-env:
        type: environment
        default: staging

jobs:
  echo:
    runs-on: ubuntu-latest
    environment: ${{inputs.target-env}}
    env:
      my-env-var: ${{vars.MY_ENV_VAL || 'default value'}}
    steps:
      - name: Echo vars
        run: |
          echo "Env var: ${{env.my-env-var}}"