name: 17 - Custom Actions (Docker)

on:
  workflow_dispatch:
    inputs:
      url:
        type: string
        default: 'https://www.google.com'

jobs:
  ping-url:
    runs-on: ubuntu-latest
    steps:
      # actions/checkout@v4: to check out the repository
      - uses: actions/checkout@v4
      - name: Ping URL
        uses: ./.github/actions/docker-ping-url
        with:
          ping-url: ${{inputs.url}}
