name: 19 - Concurrency Management

on:
  workflow_dispatch:

concurrency:
  # Any name is fine, but it's a good practise to avoid generic names, in order to conflict with other workflows
  group: ${{github.workflow}} - ${{github.ref}}

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: action/checkout@v4
      - name: Ping URL
        id: ping-url
        uses: ./.github/actions/docker-ping-url
        with:
          url: https://www.some-invalid-url.com
          max_trials: 20
          delay: 5